sonar.projectKey=rgkim-hsu_Smart-Greenhouse-Monitoring-System
sonar.organization=rgkim-hsu
sonar.projectName=Smart Greenhouse Monitoring System (Django)
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/migrations/**,**/venv/**,**/__pycache__/**,**/*.pyc,**/static/**,**/media/**,**/node_modules/**
sonar.python.version=3.8,3.9,3.10

